package com.foodopia.backend.rest.v1.errorHandling;

public enum ErrorCode {

    INVALID_PASSWORD,
    INVALID_USERNAME,
    AUTHENTICATION_FAILED,
    USER_ALREADY_REGISTERED,
    UNREGISTERED_USER,
    INPUT_VALIDATION_ERROR,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
}
